# Generated by Django 2.2.17 on 2020-11-11 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teatri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequenze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_f', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=200)),
                ('freq', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_hashtag', models.CharField(max_length=200)),
                ('freq_h', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casual', models.IntegerField()),
                ('professional', models.IntegerField()),
                ('designed', models.IntegerField()),
                ('grafica', models.IntegerField()),
                ('gruppo', models.IntegerField()),
                ('singolo', models.IntegerField()),
                ('scena', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profili',
            fields=[
                ('nome', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('testo', models.TextField()),
                ('parole', models.IntegerField()),
                ('vocabolario', models.IntegerField()),
                ('n_hashtag', models.IntegerField()),
                ('v_hashtag', models.IntegerField()),
                ('n_tag', models.IntegerField()),
                ('v_tag', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tag', models.CharField(max_length=200)),
                ('freq_t', models.IntegerField()),
                ('Id_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teatri.Profili')),
            ],
        ),
        migrations.CreateModel(
            name='Teatri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_teatro', models.CharField(max_length=200)),
                ('cat_foto', models.CharField(max_length=200)),
                ('soggetto', models.CharField(max_length=200)),
                ('codifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teatri.Profili')),
            ],
        ),
        migrations.CreateModel(
            name='ValMedi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_medi', models.IntegerField()),
                ('parole_medie', models.IntegerField()),
                ('caratteri_medi', models.IntegerField()),
                ('hashtag_medi', models.IntegerField()),
                ('nome_medi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teatri.Profili')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='img',
            name='Id_img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teatri.Profili'),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='Id_hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teatri.Profili'),
        ),
        migrations.AddField(
            model_name='frequenze',
            name='Id_freq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teatri.Profili'),
        ),
    ]
