# Generated by Django 2.2.17 on 2020-11-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teatri', '0002_auto_20201111_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='teatri',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valmedi',
            name='tag_medi',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
